name: "PR Checks"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: "npm ci"
      run: npm ci

    - name: "npm run build"
      run: npm run build

    - name: "Setup poetry using this branch's action"
      uses: "./"

    - run: "poetry --help"
